query Team($id: Int!) {
    team(teamId: $id) {
        teamId
        city
        teamName
        finalStandings {
            edges {
                node {
                    teamId
                    year
                    standing
                }
            }
        }
        currentPlayers {
            edges {
                node {
                    playerId
                    lastName
                    firstName
                    position
                }
            }
        }
    }
}