language: python
notifications: false
sudo: required

services:
  - docker

before_install:
  - docker build -t python-web .

install:
  - npm install

script:
  - npm run build

after_success:
  - if [ "$TRAVIS_BRANCH" == "feature/travis" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://registry.hub.docker.com;
    docker tag python-web cheng93/python-web:test;
    docker push cheng93/python-web:test;
    fi