language: python
notifications: false
sudo: required

services:
  - docker

before_install:
  - docker build -t python-web .

install:
  - npm install

script:
  - npm run build

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cheng93/python-web:$TRAVIS_BRANCH;