language: python
python:
  - "3.6"

notifications: false
sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build

after_success:
  - docker build -t python-web .
  - if [ "$TRAVIS_BRANCH" == "feature/travis" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
    docker tag python-web $DOCKER_REPO/python-web:test;
    docker push $DOCKER_REPO/python-web:test;
    fi