language: python
python:
  - "3.6"

notifications:
  email: false

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build
  - npm test

after_success:
  - docker build -t python-web .
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
    docker tag python-web $DOCKER_REPO/python-web:dev;
    docker push $DOCKER_REPO/python-web:dev;
    fi