language: python
python:
  - "3.6"

notifications:
  email: false

sudo: required

services:
  - docker

install:
  - yarn install

script:
  - yarn run build
  - yarn test

after_success:
  - docker build -t python-web .
  - bash ./scripts/travis_docker.sh