version: "3"
services:
  postgres:
    image: postgres:9.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    ports:
      - "5432:5432"
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "false"
    networks:
      - webnet
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./.data/elasticsearch:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    ports:
      - "5602:5601"
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:5.4.0
  #   volumes:
  #     - ./:/app
  #     - log:/var/log/python-web
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - webnet
  #   environment:
  #     path.config: "/app/logstash.conf"
  #     ELASTICSEARCH_URL: "elasticsearch:9200"
  #     ELASTICSEARCH_USER: "elastic"
  #     ELASTICSEARCH_PASSWORD: "changeme"
  #     xpack.monitoring.elasticsearch.username: "elastic"
networks:
  webnet: