version: "3"
services:
  web:
    image: cheng93/python-web:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  postgres:
    image: postgres:9.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - webnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:

