version: "3"
services:
  web:
    build: .
    volumes: 
      - /src
    ports:
      - "8000:80"
    environment:
      DEBUG: "true"
      DVDRENTAL_CONNECTION_STRING: "postgresql://postgres@postgres:5432/dvdrental"
  postgres:
    ports:
      - "2345:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"