version: "3"
services:
  postgres:
    image: postgres:9.6.5
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    ports:
      - "5432:5432"
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "false"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    networks:
      - webnet
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./.data/elasticsearch:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    ports:
      - "5602:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    ports:
      - "31311:8080"
    environment:
      ELASTICSEARCH_URL: "elasticsearch:9200"
      ELASTICSEARCH_USER: "elastic"
      ELASTICSEARCH_PASSWORD: "changeme"
  vault:
    image: vault:0.9.1
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    ports:
      - "8200:8200"
    volumes: 
      - "./.data/vault:/vault/file"
      - "./vault.json:/vault/config/vault.json"
networks:
  webnet: