version: "3"
services:
  web:
    image: cheng93/python-web:latest
    volumes:
      - web:/app
      - log:/var/log/python-web
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      LOGGING_DIRECTORY: "/var/log/python-web/"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  postgres:
    image: postgres:9.6.2
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - webnet
    environment:
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "true"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    volumes:
      - web:/app
      - log:/var/log/python-web
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    environment:
      path.config: "/app/logstash.conf"
networks:
  webnet:
volumes:
  web:
  log: